project_id = "vyoxcjzahqbtwvthknvi"

[functions.delete-user]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.log-login-attempt]
verify_jwt = false

[functions.manage-session]
verify_jwt = false

[functions.send-notification]
verify_jwt = false
